{
 "title": "Spring Boot 4 - Pokemon API Observability",
 "tags": [
  "spring-boot-4",
  "pokemon",
  "http-service-client"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS (API Pokemon)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_milliseconds_count[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latence PokeAPI (client HTTP)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_client_requests_milliseconds_sum[1m]))\n/\nsum by (uri) (rate(http_client_requests_milliseconds_count[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latence API Pokemon (serveur)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_sum{uri=\"/api/pokemon/{name}\"}[1m]))\n/\nsum(rate(http_server_requests_milliseconds_count{uri=\"/api/pokemon/{name}\"}[1m]))",
     "legendFormat": "/api/pokemon/{name}"
    }
   ]
  },
  {
   "title": "Taux d'erreur PokeAPI (client HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_milliseconds_count{status!=\"200\"}[5m]))\n/\nsum(rate(http_client_requests_milliseconds_count[5m]))",
     "legendFormat": "Erreur PokeAPI"
    }
   ]
  }
 ]
}